backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

# logo_url: https://help.waysagency.nl/images/logo/Ways-Agency-Logo.svg

locale: "en"
show_preview_links: true

collections:
  - name: "e-mail"
    label: "E-mail"
    folder: "content/e-mail"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      # Publish date
      - { label: "Publish date", name: "publish-date", widget: "datetime" }

      # Categories
      - label: "Categories"
        name: "categorie"
        description: "Please check all categories that may apply."
        widget: "object"
        collapsed: true
        fields:
          - { label: "Internship", name: "internship", widget: "boolean" }
          - {
              label: "Graduation project",
              name: "graduation-project",
              widget: "boolean",
            }
          - { label: "Freelance", name: "freelance", widget: "boolean" }
          - { label: "Paid", name: "paid", widget: "boolean" }
          - { label: "Unpaid", name: "unpaid", widget: "boolean" }
          - { label: "Research", name: "research", widget: "boolean" }
          - { label: "Design", name: "design", widget: "boolean" }
          - { label: "Development", name: "development", widget: "boolean" }

      # Languages
      - label: "Languages"
        name: "languages"
        description: "Project language preference."
        widget: "object"
        collapsed: true
        fields:
          - {
              label: "English or Dutch",
              name: "english-or-dutch",
              widget: "boolean",
            }
          - { label: "Only English", name: "only-english", widget: "boolean" }
          - { label: "Only Dutch", name: "only-dutch", widget: "boolean" }

      # Project title
      - { label: "Project title", name: "projec-title", widget: "string" }

      # Project description
      - {
          label: "Project description",
          name: "project-description",
          widget: "markdown",
        }

      # Estimated duration
      - {
          label: "Estimated duration",
          name: "estimated-duration",
          widget: "text",
        }

      # Company name
      - { label: "Company name", name: "company-name", widget: "string" }

      # Company website
      - { label: "Company website", name: "company-website", widget: "string" }

      # Contact name
      - { label: "Contact name", name: "contact-name", widget: "string" }

      # Contact email
      - { label: "Contact email", name: "contact-email", widget: "string" }

      # Contact phone number
      - {
          label: "Contact phone number",
          name: "contact-phone-number",
          widget: "string",
        }
